version: "3.6"

services:
  rabbitmq:
    image: rabbitmq:3.8.3-management-alpine
    hostname: my-rabbit
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:6.0.4-alpine
    ports:
      - 6379:6379
